improved test pipeline integration

diff --git a/batsw b/batsw
--- a/batsw
+++ b/batsw
@@ -117,6 +117,7 @@ RUN apk \
     bash \
     curl \
     git \
+    jq \
     shadow \
     openssh-client \
     sshpass
@@ -219,7 +220,7 @@ bats() {
 
   local tag="${BATS_IMAGE_LOCAL_TAG:-bats:local}"
   if [ "${BATS_IMAGE_ID-}" ]; then
-    echo "🐳 re-using existing Bats Docker image: ${BATS_IMAGE_ID}"
+    echo "🐳 re-using existing Bats Docker image: $BATS_IMAGE_ID"
   else
     if BATS_IMAGE_ID=$(
       docker_build \
@@ -228,11 +229,11 @@ bats() {
         --build-arg PGID="$(id -g)"
     ); then
       export BATS_IMAGE_ID
-      echo "🐳 using built Bats Docker image: ${BATS_IMAGE_ID}"
+      echo "🐳 using built Bats Docker image: $BATS_IMAGE_ID"
     elif [ "$(docker image ls --quiet "$tag")" ]; then
       BATS_IMAGE_ID="$tag"
       export BATS_IMAGE_ID
-      echo " $(tput setaf 11)⚠$(tput sgr0) failed to build Bats Docker image; re-using previous build: ${BATS_IMAGE_ID}"
+      echo " $(tput setaf 11)⚠$(tput sgr0) failed to build Bats Docker image; re-using previous build: $BATS_IMAGE_ID"
     else
       die "Failed to build Bats Docker image and no previous build to re-use"
     fi
@@ -247,7 +248,7 @@ bats() {
   )
 
   echo "$(tput setaf 7) ℹ$(tput sgr0) bats command line: bats" "${BATS_ARGS[@]+"${BATS_ARGS[@]}"}"
-  docker run --rm --name "bats-$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 3 || true)" \
+  docker run --rm --name "bats-$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom 2>/dev/null | head -c 3 || true)" \
     -e TERM="${TERM-}" \
     -e TMPDIR="${PWD:?}/${BATS_TMPDIR%${PWD}}" \
     -v /var/run/docker.sock:/var/run/docker.sock \
@@ -272,6 +273,8 @@ bats() {
 #   *      - bats arguments
 # bashsupport disable=BP2001,BP5006
 main() {
+  TERM=${TERM:-dumb}
+  export TERM
   local -r BATS_CMD=bats
 
   local -a BATS_ARGS=()
